package br.com.projeto;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import br.com.projeto.model.Filmes;
import br.com.projeto.model.Usuario;
import br.com.projeto.repository.FilmeRepository;
import br.com.projeto.repository.UsuarioRepository;

@SpringBootApplication
public class ProjetoDesafioApplication {

	
	@Autowired
	private UsuarioRepository repository;
	
	@PostConstruct
	public void initUsuarios() {
		List<Usuario> usuarios = Stream.of(
				new Usuario(132,"pedro","123"),
				new Usuario(133,"marcia","123"),
				new Usuario(134,"admin","123")
				
				
				).collect(Collectors.toList());
		repository.saveAll(usuarios);
	}
	
	public static void main(String[] args) {
		SpringApplication.run(ProjetoDesafioApplication.class, args);
	}
	
	@Bean
	CommandLineRunner commandLineRunner(FilmeRepository filmeRepository) {
		return args-> {
			String json ="[{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/k2twTjSddgLc1oFFHVibfxp2kQV.jpg\","
					+ "    \"genre_ids\": 45,"
					+ "    \"id\": 524434,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Eternals\","
					+ "    \"overview\": \"The Eternals are a team of ancient aliens who have been living on Eart\","
					+ "    \"popularity\": 10950.444,"
					+ "    \"poster_path\": \"/b6qUu00iIIkXX13szFy7d0CyNcg.jpg\","
					+ "    \"release_date\": \"2021-11-03\","
					+ "    \"title\": \"Eternals\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 7.3,"
					+ "    \"vote_count\": 3308"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/m3Ys7UDzUzOyoPYKzp4GhKKokUr.jpg\","
					+ "    \"genre_ids\": 12,"
					+ "    \"id\": 585083,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Hotel Transylvania: Transformania\","
					+ "    \"overview\": \"When Van Helsing's mysterious invention, the \\\"Monsterfication Ray,crazy.\","
					+ "    \"popularity\": 10279.59,"
					+ "    \"poster_path\": \"/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg\","
					+ "    \"release_date\": \"2022-01-13\","
					+ "    \"title\": \"Hotel Transylvania: Transformania\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 7.7,"
					+ "    \"vote_count\": 909"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg\","
					+ "    \"genre_ids\": 45,"
					+ "    \"id\": 634649,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Spider-Man: No Way Home\","
					+ "    \"overview\": \"Peter Parker is unmasked and no longer  it truly means to be Spider-Man.\","
					+ "    \"popularity\": 7679.11,"
					+ "    \"poster_path\": \"/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg\","
					+ "    \"release_date\": \"2021-12-15\","
					+ "    \"title\": \"Spider-Man: No Way Home\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 8.5,"
					+ "    \"vote_count\": 5153"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg\","
					+ "    \"genre_ids\":10,"
					+ "    \"id\": 438695,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Sing 2\","
					+ "    \"overview\": \"Buster and his new cast now hade him to return to the stage.\","
					+ "    \"popularity\": 5731.286,"
					+ "    \"poster_path\": \"/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg\","
					+ "    \"release_date\": \"2021-12-01\","
					+ "    \"title\": \"Sing 2\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 8.3,"
					+ "    \"vote_count\": 1216"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg\","
					+ "    \"genre_ids\": 150,"
					+ "    \"id\": 568124,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Encanto\","
					+ "    \"overview\": \"The tale of an extraordinary family's last hope.\","
					+ "    \"popularity\": 5456.539,"
					+ "    \"poster_path\": \"/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg\","
					+ "    \"release_date\": \"2021-11-24\","
					+ "    \"title\": \"Encanto\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 7.8,"
					+ "    \"vote_count\": 3270"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg\","
					+ "    \"genre_ids\": 20,"
					+ "    \"id\": 425909,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Ghostbusters: Afterlife\","
					+ "    \"overview\": \"When a single mom and her twoecret legacy their grandfather left behind.\","
					+ "    \"popularity\": 4384.78,"
					+ "    \"poster_path\": \"/sg4xJaufDiQl7caFEskBtQXfD4x.jpg\","
					+ "    \"release_date\": \"2021-11-11\","
					+ "    \"title\": \"Ghostbusters: Afterlife\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 7.7,"
					+ "    \"vote_count\": 1435"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/o76ZDm8PS9791XiuieNB93UZcRV.jpg\","
					+ "    \"genre_ids\":70,"
					+ "    \"id\": 460458,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Resident Evil: Welcome to Raccoon City\","
					+ "    \"overview\": \"Once the booming home of phar behind Umbrella and make it through the night.\","
					+ "    \"popularity\": 4205.271,"
					+ "    \"poster_path\": \"/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg\","
					+ "    \"release_date\": \"2021-11-24\","
					+ "    \"title\": \"Resident Evil: Welcome to Raccoon City\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 6.1,"
					+ "    \"vote_count\": 964"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/t4To8feUSysyBs4tlBAbXIrKlCv.jpg\","
					+ "    \"genre_ids\":33,"
					+ "    \"id\": 860623,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Last Man Down\","
					+ "    \"overview\": \"After civilization succumbs to a deadly phe man that murdered his wife some years ago.\","
					+ "    \"popularity\": 4097.075,"
					+ "    \"poster_path\": \"/tBP2yKtoWUjx8cD82qhFAoBbsSo.jpg\","
					+ "    \"release_date\": \"2021-10-19\","
					+ "    \"title\": \"Last Man Down\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 6.8,"
					+ "    \"vote_count\": 135"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg\","
					+ "    \"genre_ids\": 50,"
					+ "    \"id\": 624860,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"The Matrix Resurrections\","
					+ "    \"overview\": \"Plagued by strange memories, Neo's life takes inside the Matrix.\","
					+ "    \"popularity\": 3373.928,"
					+ "    \"poster_path\": \"/8c4a8kE7PizaGQQnditMmI1xbRp.jpg\","
					+ "    \"release_date\": \"2021-12-16\","
					+ "    \"title\": \"The Matrix Resurrections\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 6.9,"
					+ "    \"vote_count\": 2409"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg\","
					+ "    \"genre_ids\":17,"
					+ "    \"id\": 580489,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Venom: Let There Be Carnage\","
					+ "    \"overview\": \"After finding a host body in investigative repCletus Kasady.\","
					+ "    \"popularity\": 2688.01,"
					+ "    \"poster_path\": \"/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg\","
					+ "    \"release_date\": \"2021-09-30\","
					+ "    \"title\": \"Venom: Let There Be Carnage\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 7.1,"
					+ "    \"vote_count\": 5947"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/AmLpWYm9R3Ur2FLPgj5CH3wR8wp.jpg\","
					+ "    \"genre_ids\":12,"
					+ "    \"id\": 739413,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Mother/Android\","
					+ "    \"overview\": \"Georgia and her boyfriend Sam go on a treacherefore giving birth.\","
					+ "    \"popularity\": 2248.582,"
					+ "    \"poster_path\": \"/rO3nV9d1wzHEWsC7xgwxotjZQpM.jpg\","
					+ "    \"release_date\": \"2021-12-17\","
					+ "    \"title\": \"Mother/Android\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 5.9,"
					+ "    \"vote_count\": 301"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/dK12GIdhGP6NPGFssK2Fh265jyr.jpg\","
					+ "    \"genre_ids\": 55,"
					+ "    \"id\": 512195,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Red Notice\","
					+ "    \"overview\": \"An Interpol-issued Red Notice is a global aler's no telling what will happen.\","
					+ "    \"popularity\": 1922.857,"
					+ "    \"poster_path\": \"/lAXONuqg41NwUMuzMiFvicDET9Y.jpg\","
					+ "    \"release_date\": \"2021-11-04\","
					+ "    \"title\": \"Red Notice\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 6.8,"
					+ "    \"vote_count\": 2757"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/mo57hzhW3BcZL1f7MNteWKHsmlN.jpg\","
					+ "    \"genre_ids\":40,"
					+ "    \"id\": 763788,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Dangerous\","
					+ "    \"overview\": \"A reformed sociopath heads to a remoteess quest for vengeance.\","
					+ "    \"popularity\": 1893.46,"
					+ "    \"poster_path\": \"/vTtkQGC7qKlSRQJZYtAWAmYdH0A.jpg\","
					+ "    \"release_date\": \"2021-11-05\","
					+ "    \"title\": \"Dangerous\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 6.7,"
					+ "    \"vote_count\": 120"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/8jIRAV5KVZeIP6tjI1NuCfb9Il0.jpg\","
					+ "    \"genre_ids\":10,"
					+ "    \"id\": 566525,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Shang-Chi and the Legend of the Ten Rings\","
					+ "    \"overview\": \"Shang-Chi must confront the past he ths organization.\","
					+ "    \"popularity\": 1821.583,"
					+ "    \"poster_path\": \"/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg\","
					+ "    \"release_date\": \"2021-09-01\","
					+ "    \"title\": \"Shang-Chi and the Legend of the Ten Rings\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 7.8,"
					+ "    \"vote_count\": 5268"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/7esxXkFyl0dVD7ViR0Q6fK5VeXB.jpg\","
					+ "    \"genre_ids\": 10,"
					+ "    \"id\": 787310,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Survive the Game\","
					+ "    \"overview\": \"When cop David is injured in a drug bu-dealing mob.\","
					+ "    \"popularity\": 1495.914,"
					+ "    \"poster_path\": \"/xF1uc2pEf34X2G41wvZaF5H0V7C.jpg\","
					+ "    \"release_date\": \"2021-10-08\","
					+ "    \"title\": \"Survive the Game\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 5.9,"
					+ "    \"vote_count\": 83"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/1Wlwnhn5sXUIwlxpJgWszT622PS.jpg\","
					+ "    \"genre_ids\": 54,"
					+ "    \"id\": 585245,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Clifford the Big Red Dog\","
					+ "    \"overview\": \"As Emily struggles to fit in at home aal love.\","
					+ "    \"popularity\": 1352.148,"
					+ "    \"poster_path\": \"/oifhfVhUcuDjE61V5bS5dfShQrm.jpg\","
					+ "    \"release_date\": \"2021-11-10\","
					+ "    \"title\": \"Clifford the Big Red Dog\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 7.4,"
					+ "    \"vote_count\": 910"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/9fzNf2QcsHVvdx5g5QUOgAWpADw.jpg\","
					+ "    \"genre_ids\":10,"
					+ "    \"id\": 516329,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Antlers\","
					+ "    \"overview\": \"A small-town Oregon teening consequences.\","
					+ "    \"popularity\": 1351.551,"
					+ "    \"poster_path\": \"/cMch3tiexw3FdOEeZxMWVel61Xg.jpg\","
					+ "    \"release_date\": \"2021-10-28\","
					+ "    \"title\": \"Antlers\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 6.4,"
					+ "    \"vote_count\": 383"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg\","
					+ "    \"genre_ids\": 12,"
					+ "    \"id\": 635302,"
					+ "    \"original_language\": \"ja\","
					+ "    \"original_title\": \"劇場版「鬼滅の刃」無限列車編\","
					+ "    \"overview\": \"Tanjirō Kamado, joined who oppose it!\","
					+ "    \"popularity\": 1309.006,"
					+ "    \"poster_path\": \"/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg\","
					+ "    \"release_date\": \"2020-10-16\","
					+ "    \"title\": \"Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 8.4,"
					+ "    \"vote_count\": 2055"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/1BqX34aJS5J8PefVnQSfQIEPfkl.jpg\","
					+ "    \"genre_ids\":20,"
					+ "    \"id\": 826749,"
					+ "    \"original_language\": \"en\","
					+ "    \"original_title\": \"Fortress\","
					+ "    \"overview\": \"The story revolves arod his son to save the day.\","
					+ "    \"popularity\": 1215.929,"
					+ "    \"poster_path\": \"/vQxtoPJVfpHgL7DCg9hQFZKDWJa.jpg\","
					+ "    \"release_date\": \"2021-12-17\","
					+ "    \"title\": \"Fortress\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 6.4,"
					+ "    \"vote_count\": 124"
					+ "},"
					+ "{"
					+ "    \"adult\": false,"
					+ "    \"backdrop_path\": \"/xGrTm3J0FTafmuQ85vF7ZCw94x6.jpg\","
					+ "    \"genre_ids\": 12,"
					+ "    \"id\": 589761,"
					+ "    \"original_language\": \"ru\","
					+ "    \"original_title\": \"Чернобыль\","
					+ "    \"overview\": \"The aftermath of a shos is their story.\","
					+ "    \"popularity\": 1080.917,"
					+ "    \"poster_path\": \"/AmJLuHjxPdIJO6vmymeWADG6jK5.jpg\","
					+ "    \"release_date\": \"2021-04-15\","
					+ "    \"title\": \"Chernobyl: Abyss\","
					+ "    \"video\": false,"
					+ "    \"vote_average\": 6.2,"
					+ "    \"vote_count\": 277"
					+ "}"
					+ "]";
			final ObjectMapper objectMapper = new ObjectMapper();
			List<Filmes> filmeList = objectMapper.readValue(json,new TypeReference<List<Filmes>>() {});
			filmeRepository.saveAll(filmeList);
		};
	}
	
}
